export { type AgUiEventMapper, type AgUiEventMapperOptions, createAgUiEventMapper } from "./ag-ui-mapper.js";
export { type AgUiA2AServer, type AgUiA2AServerTaskInput, type CreateAgUiA2AServerOptions, createAgUiA2AServer } from "./a2a-server.js";
export {
  A2UI_ACTIVITY_TYPE,
  A2UI_ERROR_EVENT,
  A2UI_OPERATIONS_KEY,
  A2UI_VERSION,
  type AgUiA2UiAction,
  type AgUiA2UiLimitOptions,
  type AgUiA2UiOptions,
  type AgUiA2UiPainter,
  type ResolvedAgUiA2UiLimits,
  createAgUiA2UiPainter,
  DEFAULT_MAX_A2UI_COMPONENT_DEPTH,
  DEFAULT_MAX_A2UI_OPERATION_BYTES,
  DEFAULT_MAX_A2UI_OPS_PER_MESSAGE,
  DEFAULT_MAX_A2UI_SURFACES_PER_RUN,
  extractAgUiA2UiActions,
  HARD_MAX_A2UI_COMPONENT_DEPTH,
  HARD_MAX_A2UI_OPERATION_BYTES,
  HARD_MAX_A2UI_OPS_PER_MESSAGE,
  HARD_MAX_A2UI_SURFACES_PER_RUN,
  resolveAgUiA2UiLimits,
} from "./a2ui.js";
export {
  type AgUiA2AAdapter,
  type AgUiA2APartProjectionInput,
  type AgUiA2ASelection,
  type AgUiA2ASelectionInput,
  type CreateAgUiA2AAdapterOptions,
  createAgUiA2AAdapter,
} from "./a2a.js";
export { AgUiError, type AgUiErrorCode } from "./errors.js";
export {
  type CreateReasoningEncryptedValueOptions,
  createReasoningEncryptedValue,
} from "./encrypted-value.js";
export {
  type AgUiMcpAppAuthorizationInput,
  type AgUiMcpAppCallContext,
  type AgUiMcpAppSandbox,
  type CreateAgUiMcpAppHandlerOptions,
  createAgUiMcpAppHandler,
  createAgUiMcpAppSandbox,
} from "./mcp-apps.js";
export {
  type AgUiMcpAppEffectContext,
  type ReconcileAppEffectInput,
  deriveAppEffectKey,
  hashJson,
  reconcileAppEffect,
} from "./effect-recovery.js";
export {
  type AgUiMcpAdapter,
  type AgUiMcpPrepareInput,
  type AgUiMcpToolSelectionInput,
  type CreateAgUiMcpAdapterOptions,
  createAgUiMcpAdapter,
} from "./mcp.js";
export {
  type AgUiAuthorizationInput,
  type AgUiFrontendToolHandoff,
  type AgUiFrontendToolPolicyInput,
  type AgUiHandler,
  type AgUiInputOptions,
  type AgUiInputProjection,
  type AgUiInputProjectorInput,
  type AgUiInterruptOptions,
  type AgUiInterruptResume,
  type AgUiPreparedInput,
  type AgUiRunResolutionRequest,
  type CreateAgUiHandlerOptions,
  createAgUiHandler,
  resolveAgUiCapabilities,
} from "./handler.js";
export {
  type AgUiLimitOptions,
  DEFAULT_AG_UI_LIMITS,
  DEFAULT_MAX_ACTIVITY_BYTES,
  DEFAULT_MAX_CURSOR_BYTES,
  DEFAULT_MAX_ERROR_BYTES,
  DEFAULT_MAX_EVENT_BYTES,
  DEFAULT_MAX_INPUT_CONTEXT_BYTES,
  DEFAULT_MAX_INPUT_CONTEXTS,
  DEFAULT_MAX_INPUT_INTERRUPTS,
  DEFAULT_MAX_INPUT_MEDIA_BYTES,
  DEFAULT_MAX_INPUT_MEDIA_PARTS,
  DEFAULT_MAX_INPUT_MESSAGES,
  DEFAULT_MAX_INPUT_TEXT_BYTES,
  DEFAULT_MAX_INPUT_TOOL_BYTES,
  DEFAULT_MAX_INPUT_TOOLS,
  DEFAULT_MAX_JSON_ARRAY_ITEMS,
  DEFAULT_MAX_JSON_DEPTH,
  DEFAULT_MAX_JSON_PROPERTIES,
  DEFAULT_MAX_PATCH_OPERATIONS,
  DEFAULT_MAX_QUEUED_EVENTS,
  DEFAULT_MAX_RAW_EVENT_BYTES,
  DEFAULT_MAX_REASONING_BYTES,
  DEFAULT_MAX_REPLAY_EVENTS,
  DEFAULT_MAX_REQUEST_BYTES,
  DEFAULT_MAX_STATE_BYTES,
  DEFAULT_MAX_STREAM_BYTES,
  DEFAULT_MAX_STREAM_EVENTS,
  DEFAULT_MAX_TEXT_BYTES,
  DEFAULT_REQUEST_TIMEOUT_MS,
  HARD_AG_UI_LIMITS,
  HARD_MAX_ACTIVITY_BYTES,
  HARD_MAX_CURSOR_BYTES,
  HARD_MAX_ERROR_BYTES,
  HARD_MAX_EVENT_BYTES,
  HARD_MAX_INPUT_CONTEXT_BYTES,
  HARD_MAX_INPUT_CONTEXTS,
  HARD_MAX_INPUT_INTERRUPTS,
  HARD_MAX_INPUT_MEDIA_BYTES,
  HARD_MAX_INPUT_MEDIA_PARTS,
  HARD_MAX_INPUT_MESSAGES,
  HARD_MAX_INPUT_TEXT_BYTES,
  HARD_MAX_INPUT_TOOL_BYTES,
  HARD_MAX_INPUT_TOOLS,
  HARD_MAX_JSON_ARRAY_ITEMS,
  HARD_MAX_JSON_DEPTH,
  HARD_MAX_JSON_PROPERTIES,
  HARD_MAX_PATCH_OPERATIONS,
  HARD_MAX_QUEUED_EVENTS,
  HARD_MAX_RAW_EVENT_BYTES,
  HARD_MAX_REASONING_BYTES,
  HARD_MAX_REPLAY_EVENTS,
  HARD_MAX_REQUEST_BYTES,
  HARD_MAX_STATE_BYTES,
  HARD_MAX_STREAM_BYTES,
  HARD_MAX_STREAM_EVENTS,
  HARD_MAX_TEXT_BYTES,
  HARD_REQUEST_TIMEOUT_MS,
  type ResolvedAgUiLimits,
  resolveAgUiLimits,
} from "./limits.js";
export type {
  AgUiActivityDelta,
  AgUiActivitySnapshot,
  AgUiCustomProjection,
  AgUiProjection,
  Awaitable,
  AgUiRawProjection,
  AgUiReasoningProjection,
} from "./projection.js";
export { type CoWorkProjectionOptions, projectAgUiJson, projectAgUiPatch, projectCoWorkEvent } from "./projection.js";
export {
  type AgUiStateStore,
  type CreateActivityFromToolProgressProjectionOptions,
  type CreateMessagesFromSessionProjectionOptions,
  type CreateStateFromStoreProjectionOptions,
  composeAgUiProjections,
  createActivityFromToolProgressProjection,
  createMessagesFromSessionProjection,
  createStateFromStoreProjection,
  DEFAULT_MAX_PROJECTOR_MESSAGES,
  HARD_MAX_PROJECTOR_MESSAGES,
  jsonDiff,
} from "./projectors.js";
export {
  type AgentEventSourceAgUiReplayOptions,
  type AgUiReplay,
  type AgUiReplayEvent,
  type AgUiReplayPage,
  type AgUiReplayRequest,
  type CoWorkReplay,
  type CoWorkReplayOptions,
  type CoWorkReplayPage,
  type CoWorkReplayRequest,
  type CoWorkSource,
  createAgentEventSourceAgUiReplay,
  createCoWorkReplay,
  createPersistenceAgUiReplay,
  type PersistenceAgUiReplayOptions,
} from "./replay.js";
export type { AgUiAuthorization, AgUiRunReference, CoWorkContext, CoWorkEvent, CoWorkKind } from "./types.js";

// Task 14: reference renderer subpath (@arnilo/prism-ag-ui/renderer).
// Type-only re-exports; runtime DOM code stays behind the subpath so the main
// entry remains runtime-agnostic.
export type {
  A2UiCatalog,
  A2UiComponentModel,
  A2UiComponentRenderer,
  A2UiRenderContext,
  A2UiRenderError,
  A2UiRenderer,
  A2UiSurfaceModel,
  CreateA2UiRendererOptions,
  Dom,
  DomNode,
} from "./renderer/index.js";

export const packageName = "@arnilo/prism-ag-ui";
