export {
  type BrowserCheckpoint,
  type BrowserCheckpointInput,
  type BrowserCheckpointLedger,
  type BrowserCheckpointLimitOptions,
  type BrowserCheckpointLimits,
  createBrowserCheckpointLedger,
  DEFAULT_MAX_CHECKPOINT_URL_BYTES,
  DEFAULT_MAX_CHECKPOINTS_PER_RUN,
  DEFAULT_MAX_DOMAIN_STATE_HASH_BYTES,
  DEFAULT_MAX_HOST_DATA_REF_BYTES,
  HARD_MAX_CHECKPOINT_URL_BYTES,
  HARD_MAX_CHECKPOINTS_PER_RUN,
  HARD_MAX_DOMAIN_STATE_HASH_BYTES,
  HARD_MAX_HOST_DATA_REF_BYTES,
  resolveBrowserCheckpointLimits,
} from "./checkpoint.js";
export {
  type BrowserDownloadOptions,
  cleanupDownloads,
  createDownloadBudget,
  type DownloadBudget,
  type DownloadMetadata,
  quarantineDownload,
  releaseDownload,
  sanitizeDownloadName,
} from "./downloads.js";
export { BrowserError, type BrowserErrorCode } from "./errors.js";
export {
  type BrowserLimitOptions,
  DEFAULT_ACTION_TIMEOUT_MS,
  DEFAULT_BROWSER_LIMITS,
  DEFAULT_CLOSE_GRACE_MS,
  DEFAULT_MAX_ACTION_INPUT_BYTES,
  DEFAULT_MAX_ACTIONS,
  DEFAULT_MAX_DIALOGS,
  DEFAULT_MAX_DOWNLOAD_AGGREGATE_BYTES,
  DEFAULT_MAX_DOWNLOAD_BYTES,
  DEFAULT_MAX_DOWNLOADS,
  DEFAULT_MAX_LISTENERS,
  DEFAULT_MAX_NETWORK_REQUESTS,
  DEFAULT_MAX_PAGES,
  DEFAULT_MAX_POPUPS,
  DEFAULT_MAX_QUEUED_ACTIONS,
  DEFAULT_MAX_REDIRECTS_PER_REQUEST,
  DEFAULT_MAX_SCREENSHOT_BYTES,
  DEFAULT_MAX_SCREENSHOT_MEGAPIXELS,
  DEFAULT_MAX_SCREENSHOTS,
  DEFAULT_MAX_SNAPSHOT_BYTES,
  DEFAULT_MAX_SNAPSHOT_DEPTH,
  DEFAULT_MAX_SNAPSHOT_REFS,
  DEFAULT_MAX_UPLOAD_AGGREGATE_BYTES,
  DEFAULT_MAX_UPLOAD_BYTES,
  DEFAULT_MAX_UPLOADS,
  DEFAULT_MAX_WEBSOCKETS,
  DEFAULT_NAVIGATION_TIMEOUT_MS,
  DEFAULT_RUN_WALL_TIME_MS,
  DEFAULT_WAIT_TIMEOUT_MS,
  HARD_ACTION_TIMEOUT_MS,
  HARD_BROWSER_LIMITS,
  HARD_CLOSE_GRACE_MS,
  HARD_MAX_ACTION_INPUT_BYTES,
  HARD_MAX_ACTIONS,
  HARD_MAX_DIALOGS,
  HARD_MAX_DOWNLOAD_AGGREGATE_BYTES,
  HARD_MAX_DOWNLOAD_BYTES,
  HARD_MAX_DOWNLOADS,
  HARD_MAX_LISTENERS,
  HARD_MAX_NETWORK_REQUESTS,
  HARD_MAX_PAGES,
  HARD_MAX_POPUPS,
  HARD_MAX_QUEUED_ACTIONS,
  HARD_MAX_REDIRECTS_PER_REQUEST,
  HARD_MAX_SCREENSHOT_BYTES,
  HARD_MAX_SCREENSHOT_MEGAPIXELS,
  HARD_MAX_SCREENSHOTS,
  HARD_MAX_SNAPSHOT_BYTES,
  HARD_MAX_SNAPSHOT_DEPTH,
  HARD_MAX_SNAPSHOT_REFS,
  HARD_MAX_UPLOAD_AGGREGATE_BYTES,
  HARD_MAX_UPLOAD_BYTES,
  HARD_MAX_UPLOADS,
  HARD_MAX_WEBSOCKETS,
  HARD_NAVIGATION_TIMEOUT_MS,
  HARD_RUN_WALL_TIME_MS,
  HARD_WAIT_TIMEOUT_MS,
  type ResolvedBrowserLimits,
  resolveBrowserLimits,
} from "./limits.js";
export { type BrowserManager, type CreateBrowserManagerOptions, createBrowserManager } from "./manager.js";
export {
  assertBrowserUrlAllowed,
  type BrowserNetworkPolicy,
  type BrowserUrlDecision,
  classifyBrowserUrl,
  classifyHost,
  createNetworkBudget,
  installNetworkRouting,
  type NetworkBudget,
} from "./network.js";
export {
  type BrowserEffectClass,
  type BrowserOperationClass,
  type BrowserRisk,
  buildBrowserExecutionAction,
  classifyBrowserOperation,
  classifyBrowserToolEffect,
  isSideEffectAction,
} from "./policy.js";
export {
  type CaptureScreenshotOptions,
  captureBoundedScreenshot,
  createScreenshotBudget,
  type ScreenshotBudget,
  type ScreenshotResult,
} from "./screenshot.js";
export {
  createSharedSandboxBrowserOptions,
  type SharedSandboxBrowserAlignment,
  type SharedSandboxBrowserOptions,
} from "./shared-sandbox.js";
export { captureAriaSnapshot, createSnapshotId, type LiveSnapshot, toSnapshotResult } from "./snapshot.js";
export {
  assertValidRef,
  normalizeTarget,
  parseSnapshotRefs,
  requireUniqueLocator,
  resolveTargetLocator,
} from "./targets.js";
export { type BrowserToolsOptions, createBrowserTools, getBrowserManagerFromTools } from "./tools.js";
export type {
  BrowserActionName,
  BrowserActRequest,
  BrowserActResult,
  BrowserDownloadInfo,
  BrowserOpenResult,
  BrowserPageInfo,
  BrowserSnapshotResult,
  BrowserTarget,
  PlaywrightBrowser,
  PlaywrightBrowserContext,
  PlaywrightDialog,
  PlaywrightDownload,
  PlaywrightLocator,
  PlaywrightPage,
  PlaywrightRequest,
  PlaywrightRoute,
  SnapshotRefInfo,
} from "./types.js";
export {
  type ApprovedUploadFile,
  approveUploadPaths,
  type BrowserUploadOptions,
  createUploadBudget,
  resolveUploadCandidate,
  type UploadBudget,
} from "./uploads.js";

export const packageName = "@arnilo/prism-browser";
