export { BrowserError, type BrowserErrorCode } from "./errors.js";
export {
  DEFAULT_BROWSER_LIMITS,
  HARD_BROWSER_LIMITS,
  DEFAULT_MAX_PAGES,
  HARD_MAX_PAGES,
  DEFAULT_MAX_ACTIONS,
  HARD_MAX_ACTIONS,
  DEFAULT_MAX_QUEUED_ACTIONS,
  HARD_MAX_QUEUED_ACTIONS,
  DEFAULT_MAX_SNAPSHOT_REFS,
  HARD_MAX_SNAPSHOT_REFS,
  DEFAULT_MAX_SNAPSHOT_DEPTH,
  HARD_MAX_SNAPSHOT_DEPTH,
  DEFAULT_MAX_SNAPSHOT_BYTES,
  HARD_MAX_SNAPSHOT_BYTES,
  DEFAULT_NAVIGATION_TIMEOUT_MS,
  HARD_NAVIGATION_TIMEOUT_MS,
  DEFAULT_ACTION_TIMEOUT_MS,
  HARD_ACTION_TIMEOUT_MS,
  DEFAULT_WAIT_TIMEOUT_MS,
  HARD_WAIT_TIMEOUT_MS,
  DEFAULT_RUN_WALL_TIME_MS,
  HARD_RUN_WALL_TIME_MS,
  DEFAULT_MAX_POPUPS,
  HARD_MAX_POPUPS,
  DEFAULT_MAX_DIALOGS,
  HARD_MAX_DIALOGS,
  DEFAULT_MAX_LISTENERS,
  HARD_MAX_LISTENERS,
  DEFAULT_MAX_ACTION_INPUT_BYTES,
  HARD_MAX_ACTION_INPUT_BYTES,
  DEFAULT_CLOSE_GRACE_MS,
  HARD_CLOSE_GRACE_MS,
  DEFAULT_MAX_NETWORK_REQUESTS,
  HARD_MAX_NETWORK_REQUESTS,
  DEFAULT_MAX_REDIRECTS_PER_REQUEST,
  HARD_MAX_REDIRECTS_PER_REQUEST,
  DEFAULT_MAX_WEBSOCKETS,
  HARD_MAX_WEBSOCKETS,
  DEFAULT_MAX_SCREENSHOTS,
  HARD_MAX_SCREENSHOTS,
  DEFAULT_MAX_SCREENSHOT_MEGAPIXELS,
  HARD_MAX_SCREENSHOT_MEGAPIXELS,
  DEFAULT_MAX_SCREENSHOT_BYTES,
  HARD_MAX_SCREENSHOT_BYTES,
  DEFAULT_MAX_UPLOADS,
  HARD_MAX_UPLOADS,
  DEFAULT_MAX_UPLOAD_BYTES,
  HARD_MAX_UPLOAD_BYTES,
  DEFAULT_MAX_UPLOAD_AGGREGATE_BYTES,
  HARD_MAX_UPLOAD_AGGREGATE_BYTES,
  DEFAULT_MAX_DOWNLOADS,
  HARD_MAX_DOWNLOADS,
  DEFAULT_MAX_DOWNLOAD_BYTES,
  HARD_MAX_DOWNLOAD_BYTES,
  DEFAULT_MAX_DOWNLOAD_AGGREGATE_BYTES,
  HARD_MAX_DOWNLOAD_AGGREGATE_BYTES,
  resolveBrowserLimits,
  type BrowserLimitOptions,
  type ResolvedBrowserLimits,
} from "./limits.js";
export { createBrowserManager, type BrowserManager, type CreateBrowserManagerOptions } from "./manager.js";
export { createBrowserTools, getBrowserManagerFromTools, type BrowserToolsOptions } from "./tools.js";
export {
  assertValidRef,
  normalizeTarget,
  parseSnapshotRefs,
  requireUniqueLocator,
  resolveTargetLocator,
} from "./targets.js";
export { captureAriaSnapshot, createSnapshotId, toSnapshotResult, type LiveSnapshot } from "./snapshot.js";
export {
  assertBrowserUrlAllowed,
  classifyBrowserUrl,
  classifyHost,
  createNetworkBudget,
  installNetworkRouting,
  type BrowserNetworkPolicy,
  type BrowserUrlDecision,
  type NetworkBudget,
} from "./network.js";
export {
  buildBrowserExecutionAction,
  classifyBrowserOperation,
  isSideEffectAction,
  type BrowserEffectClass,
  type BrowserOperationClass,
  type BrowserRisk,
} from "./policy.js";
export {
  approveUploadPaths,
  createUploadBudget,
  resolveUploadCandidate,
  type ApprovedUploadFile,
  type BrowserUploadOptions,
  type UploadBudget,
} from "./uploads.js";
export {
  cleanupDownloads,
  createDownloadBudget,
  quarantineDownload,
  releaseDownload,
  sanitizeDownloadName,
  type BrowserDownloadOptions,
  type DownloadBudget,
  type DownloadMetadata,
} from "./downloads.js";
export {
  captureBoundedScreenshot,
  createScreenshotBudget,
  type CaptureScreenshotOptions,
  type ScreenshotBudget,
  type ScreenshotResult,
} from "./screenshot.js";
export {
  createSharedSandboxBrowserOptions,
  type SharedSandboxBrowserAlignment,
  type SharedSandboxBrowserOptions,
} from "./shared-sandbox.js";
export type {
  BrowserActRequest,
  BrowserActResult,
  BrowserActionName,
  BrowserDownloadInfo,
  BrowserOpenResult,
  BrowserPageInfo,
  BrowserSnapshotResult,
  BrowserTarget,
  PlaywrightBrowser,
  PlaywrightBrowserContext,
  PlaywrightDialog,
  PlaywrightDownload,
  PlaywrightLocator,
  PlaywrightPage,
  PlaywrightRequest,
  PlaywrightRoute,
  SnapshotRefInfo,
} from "./types.js";

export const packageName = "@arnilo/prism-browser";
