import { type DocumentCaps, resolveDocumentCaps, validateByteCap, validateModelCaps } from "./caps.js";
import { DocumentsFormatError } from "./errors.js";
import { sha256Hex } from "./hash.js";
import { validateDocumentModel } from "./model-schema.js";
import type { DocumentsTelemetry } from "./telemetry.js";
import { generateDocxBytes } from "./translate/docx.js";
import { generatePptxBytes } from "./translate/pptx.js";
import { generateXlsxBytes } from "./translate/xlsx.js";
import type { DeckModel, DocModel, DocumentModel, SheetModel } from "./types.js";

export type DocumentFormat = "docx" | "xlsx" | "pptx";

export interface GenerateDocumentOptions {
  /** Target OOXML output format. Must match document kind (doc->docx, sheet->xlsx, deck->pptx). */
  readonly format: DocumentFormat;
  /** Optional caps overrides. */
  readonly caps?: DocumentCaps;
  /** Optional telemetry seam hook for recording span metrics without text leaking. */
  readonly telemetry?: DocumentsTelemetry;
}

export interface GenerateDocumentResult {
  /** In-memory spec-compliant OOXML binary bytes (PK zip container). */
  readonly bytes: Uint8Array;
  /** 64-character lowercase SHA-256 hex digest of the output bytes. */
  readonly contentHash: string;
}

/**
 * Generates an in-memory, spec-compliant OOXML document (DOCX, XLSX, or PPTX)
 * from a typed Prism Document Model.
 *
 * Enforces schema validation and element/byte caps before generation.
 * Operates purely in memory with zero filesystem or network I/O.
 */
export async function generateDocument(model: DocumentModel, options: GenerateDocumentOptions): Promise<GenerateDocumentResult> {
  const { format, caps: userCaps, telemetry } = options;

  const span = telemetry?.startSpan("documents.generate", {
    "documents.kind": model?.kind ?? "unknown",
    "documents.format": format,
  });

  try {
    if (model.kind === "doc" && format !== "docx") {
      throw new DocumentsFormatError(`unsupported format "${format}" for doc model (expected "docx")`);
    }
    if (model.kind === "sheet" && format !== "xlsx") {
      throw new DocumentsFormatError(`unsupported format "${format}" for sheet model (expected "xlsx")`);
    }
    if (model.kind === "deck" && format !== "pptx") {
      throw new DocumentsFormatError(`unsupported format "${format}" for deck model (expected "pptx")`);
    }

    // 1. Trust boundary: validate model against Draft-07 schema and structural invariants
    validateDocumentModel(model);

    // 2. Resolve caps and check element counts before paying generation cost
    const caps = resolveDocumentCaps(userCaps);
    validateModelCaps(model, caps);

    // 3. Translate and generate in-memory OOXML zip bytes
    let bytes: Uint8Array;
    switch (model.kind) {
      case "doc":
        bytes = generateDocxBytes(model as DocModel);
        break;
      case "sheet":
        bytes = generateXlsxBytes(model as SheetModel);
        break;
      case "deck":
        bytes = generatePptxBytes(model as DeckModel);
        break;
      default:
        throw new DocumentsFormatError(`unsupported document kind: "${String((model as DocumentModel).kind)}"`);
    }

    // 4. Validate output byte length against maxBytes cap
    validateByteCap(bytes.byteLength, caps);

    // 5. Compute SHA-256 contentHash over the generated bytes
    const contentHash = sha256Hex(bytes);

    span?.setAttribute("documents.bytes", bytes.byteLength);

    return {
      bytes,
      contentHash,
    };
  } catch (err) {
    span?.recordError();
    throw err;
  } finally {
    span?.end();
  }
}
