import { randomUUID } from "node:crypto";
import {
  type OAuthClientProvider,
  type OAuthDiscoveryState,
  auth as sdkAuth,
  selectClientAuthMethod,
} from "@modelcontextprotocol/sdk/client/auth.js";
import type {
  AuthorizationServerMetadata,
  OAuthClientInformationMixed,
  OAuthClientMetadata,
  OAuthTokens,
} from "@modelcontextprotocol/sdk/shared/auth.js";

/**
 * MCP OAuth client integration (plan 011 Task 3).
 *
 * `createMcpClientAuth` builds an SDK `OAuthClientProvider` (wired into
 * `StreamableHTTPClientTransport` via `authProvider`) with Prism's policy and
 * persistence seams:
 *
 * - RFC 9728 protected-resource metadata discovery, RFC 8414 authorization
 *   server metadata (both via the SDK's `auth()` orchestrator; every discovery
 *   HTTP request is SSRF-checked, https-only except explicit loopback opt-in,
 *   DNS-pinned, redirect-free, and byte-bounded by `createMcpOAuthFetch`).
 * - RFC 8707 resource binding: `validateResourceURL` refuses any resource
 *   whose origin differs from the MCP server origin (confused-deputy denial,
 *   `ERR_PRISM_MCP_OAUTH_AUDIENCE`). The bearer token is attached only to
 *   requests against allow-listed server origins (SDK `_commonHeaders`), so a
 *   token is never sent to a different origin.
 * - RFC 8414 issuer/origin coherence: discovered authorization server
 *   metadata whose `issuer` origin differs from the discovered AS URL fails
 *   closed (`ERR_PRISM_MCP_OAUTH_ORIGIN`).
 * - Host-chosen client registration: `static` client credentials or RFC 7591
 *   dynamic registration (SDK `registerClient` with the host's
 *   `clientMetadata`); registered clients are persisted via `McpClientAuthState`.
 * - Mandatory PKCE (S256) and OAuth `state` are generated by the SDK/provider;
 *   the verifier/state round-trip is persisted through `McpClientAuthState`.
 * - Token refresh (SDK `refreshAuthorization` on 401/expiry), scope challenges
 *   (SDK 403 `insufficient_scope` re-auth), and `revoke()` (RFC 7009 against
 *   the discovered revocation endpoint, then local invalidation).
 * - Discovery state is cached bounded by `discoveryCacheTtlMs` (single entry
 *   per client) and persisted through the state seam; persisted discovery is
 *   revalidated on save (`issuer` origin check).
 *
 * Error codes (frozen): ERR_PRISM_MCP_OAUTH_DISCOVERY (discovery/flow
 * transport failures), ERR_PRISM_MCP_OAUTH_ORIGIN (issuer/origin drift),
 * ERR_PRISM_MCP_OAUTH_AUDIENCE (resource origin mismatch), ERR_PRISM_MCP_OAUTH_SSRF
 * (SSRF denial on discovery endpoints), ERR_PRISM_MCP_OAUTH_STATE (verifier/
 * state bounds or missing round trip), ERR_PRISM_MCP_OAUTH_TOKEN_STORE (token
 * record bounds, revocation, or persistence failures). SDK-level OAuth errors
 * (invalid_grant, invalid_client, ...) propagate as SDK `OAuthError`s.
 */

export interface McpOAuthLimitsInput {
  readonly discoveryBytes?: number;
  readonly discoveryCacheEntries?: number;
  readonly discoveryCacheTtlMs?: number;
  readonly tokenRecordBytes?: number;
  readonly stateBytes?: number;
  readonly handshakeTimeoutMs?: number;
}

export interface ResolvedMcpOAuthLimits {
  discoveryBytes: number;
  discoveryCacheEntries: number;
  discoveryCacheTtlMs: number;
  tokenRecordBytes: number;
  stateBytes: number;
  handshakeTimeoutMs: number;
}

const DEFAULT_MCP_OAUTH_LIMITS: ResolvedMcpOAuthLimits = Object.freeze({
  discoveryBytes: 64 * 1024,
  discoveryCacheEntries: 16,
  discoveryCacheTtlMs: 600_000,
  tokenRecordBytes: 16 * 1024,
  stateBytes: 4 * 1024,
  handshakeTimeoutMs: 60_000,
});

const HARD_MCP_OAUTH_LIMITS: ResolvedMcpOAuthLimits = Object.freeze({
  discoveryBytes: 256 * 1024,
  discoveryCacheEntries: 64,
  discoveryCacheTtlMs: 3_600_000,
  tokenRecordBytes: 64 * 1024,
  stateBytes: 16 * 1024,
  handshakeTimeoutMs: 300_000,
});

export function resolveMcpOAuthLimits(input: McpOAuthLimitsInput = {}): ResolvedMcpOAuthLimits {
  const out = {} as ResolvedMcpOAuthLimits;
  for (const key of Object.keys(DEFAULT_MCP_OAUTH_LIMITS) as (keyof ResolvedMcpOAuthLimits)[]) {
    const value = input[key] ?? DEFAULT_MCP_OAUTH_LIMITS[key];
    if (!Number.isSafeInteger(value) || value < 1 || value > HARD_MCP_OAUTH_LIMITS[key]) {
      throw new McpOAuthError("ERR_PRISM_MCP_OAUTH_STATE", `${key} must be a positive safe integer <= ${HARD_MCP_OAUTH_LIMITS[key]}`);
    }
    out[key] = value;
  }
  return out;
}

/** Host-chosen client registration: static credentials or RFC 7591 DCR metadata. */
export type McpOAuthRegistrationStrategy =
  | { readonly kind: "static"; readonly clientId: string; readonly clientSecret?: string }
  | { readonly kind: "dcr"; readonly clientMetadata: OAuthClientMetadata };

/**
 * Persistence seam for OAuth session material. Production hosts must back this
 * with an encrypted/keychain store (e.g. `@arnilo/prism-credentials-node`
 * `createOAuthCredentialStoreAdapter` over an encrypted or keychain store);
 * refresh tokens must never land in plaintext stores.
 */
export interface McpClientAuthState {
  loadTokens(): Promise<OAuthTokens | undefined>;
  saveTokens(tokens: OAuthTokens): Promise<void>;
  loadDiscovery(): Promise<OAuthDiscoveryState | undefined>;
  saveDiscovery(state: OAuthDiscoveryState): Promise<void>;
  loadClientInformation(): Promise<OAuthClientInformationMixed | undefined>;
  saveClientInformation(info: OAuthClientInformationMixed): Promise<void>;
  loadCodeVerifier(): Promise<string | undefined>;
  saveCodeVerifier(verifier: string): Promise<void>;
  clear(scope: "all" | "client" | "tokens" | "verifier" | "discovery"): Promise<void>;
}

export interface McpClientAuthOptions {
  /** Required persistence seam (encrypted/keychain in production). */
  readonly state: McpClientAuthState;
  readonly strategy: McpOAuthRegistrationStrategy;
  /** Scope(s) requested during authorization; refined by WWW-Authenticate challenges. */
  readonly scopes?: readonly string[];
  /** Redirect URI of the local callback endpoint for the authorization code flow. */
  readonly redirectUri?: string | URL;
  /** Invoked with the authorization URL when user interaction is required. */
  readonly onRedirectRequired?: (authorizationUrl: URL) => void | Promise<void>;
  readonly limits?: McpOAuthLimitsInput;
  /** Test seam for the base fetch used by the SDK OAuth flow. */
  readonly fetch?: typeof fetch;
  readonly now?: () => number;
}

export class McpOAuthError extends Error {
  readonly code: string;
  constructor(code: string, message: string, options?: { readonly cause?: unknown }) {
    super(message, options);
    this.name = "McpOAuthError";
    this.code = code;
  }
}

export interface McpClientAuth {
  readonly provider: OAuthClientProvider;
  /** Runs the SDK auth orchestrator (discovery, tokens/refresh, or authorization start). */
  ensureAuthorized(options?: { readonly scope?: string; readonly resourceMetadataUrl?: URL }): Promise<"AUTHORIZED" | "REDIRECT">;
  /** Completes the authorization code round trip after `onRedirectRequired`. */
  finishAuth(authorizationCode: string): Promise<void>;
  /** RFC 7009 revocation (when the AS advertises a revocation endpoint) plus local invalidation. */
  revoke(): Promise<void>;
  getTokens(): Promise<OAuthTokens | undefined>;
}

function utf8Bytes(value: unknown): number {
  return Buffer.byteLength(typeof value === "string" ? value : JSON.stringify(value), "utf8");
}

function applyClientAuth(
  headers: Headers,
  params: URLSearchParams,
  method: "client_secret_basic" | "client_secret_post" | "none",
  clientId: string,
  clientSecret?: string,
): void {
  if (method === "none") {
    params.set("client_id", clientId);
    return;
  }
  if (!clientSecret) throw new McpOAuthError("ERR_PRISM_MCP_OAUTH_TOKEN_STORE", "client authentication requires a client secret");
  if (method === "client_secret_post") {
    params.set("client_id", clientId);
    params.set("client_secret", clientSecret);
    return;
  }
  headers.set("Authorization", `Basic ${Buffer.from(`${clientId}:${clientSecret}`).toString("base64")}`);
}

class PrismOAuthClientProvider implements OAuthClientProvider {
  readonly #options: McpClientAuthOptions;
  readonly #limits: ResolvedMcpOAuthLimits;
  readonly #now: () => number;
  #discoveryCache?: { readonly state: OAuthDiscoveryState; readonly savedAt: number };
  #discoveryLoaded = false;

  constructor(
    options: McpClientAuthOptions,
    context: { readonly serverUrl: string | URL; readonly fetch: typeof fetch; readonly limits: ResolvedMcpOAuthLimits },
  ) {
    this.#options = options;
    this.#limits = context.limits;
    this.#now = options.now ?? Date.now;
  }

  get redirectUrl(): string | URL | undefined {
    return this.#options.redirectUri;
  }

  get clientMetadata(): OAuthClientMetadata {
    if (this.#options.strategy.kind === "dcr") return this.#options.strategy.clientMetadata;
    const redirectUris = this.#options.redirectUri !== undefined ? [String(this.#options.redirectUri)] : [];
    return {
      client_name: "prism-mcp",
      redirect_uris: redirectUris,
      ...(this.#options.scopes?.length ? { scope: this.#options.scopes.join(" ") } : {}),
    };
  }

  async clientInformation(): Promise<OAuthClientInformationMixed | undefined> {
    if (this.#options.strategy.kind === "static") {
      return {
        client_id: this.#options.strategy.clientId,
        ...(this.#options.strategy.clientSecret !== undefined ? { client_secret: this.#options.strategy.clientSecret } : {}),
      };
    }
    return this.#options.state.loadClientInformation();
  }

  async saveClientInformation(info: OAuthClientInformationMixed): Promise<void> {
    if (this.#options.strategy.kind !== "dcr") return;
    this.#assertRecordBytes(info, "client registration record");
    await this.#options.state.saveClientInformation(info);
  }

  async tokens(): Promise<OAuthTokens | undefined> {
    return this.#options.state.loadTokens();
  }

  async saveTokens(tokens: OAuthTokens): Promise<void> {
    this.#assertRecordBytes(tokens, "token record");
    await this.#options.state.saveTokens(tokens);
  }

  async redirectToAuthorization(authorizationUrl: URL): Promise<void> {
    if (this.#options.onRedirectRequired) {
      await this.#options.onRedirectRequired(authorizationUrl);
      return;
    }
    throw new McpOAuthError(
      "ERR_PRISM_MCP_OAUTH_STATE",
      "interactive authorization required; provide onRedirectRequired and complete finishAuth(authorizationCode)",
    );
  }

  state(): string {
    return randomUUID();
  }

  async saveCodeVerifier(codeVerifier: string): Promise<void> {
    this.#assertStateBytes(codeVerifier, "PKCE verifier");
    await this.#options.state.saveCodeVerifier(codeVerifier);
  }

  async codeVerifier(): Promise<string> {
    const verifier = await this.#options.state.loadCodeVerifier();
    if (!verifier) throw new McpOAuthError("ERR_PRISM_MCP_OAUTH_STATE", "PKCE code verifier is missing from the auth round trip");
    return verifier;
  }

  /** RFC 8707: the resource must share the MCP server origin (confused-deputy denial). */
  async validateResourceURL(serverUrl: string | URL, resource?: string): Promise<URL | undefined> {
    if (resource === undefined) return undefined;
    let parsed: URL;
    try {
      parsed = new URL(resource);
    } catch {
      throw new McpOAuthError("ERR_PRISM_MCP_OAUTH_AUDIENCE", "protected resource metadata declared an invalid resource URL");
    }
    if (parsed.origin !== new URL(serverUrl).origin) {
      throw new McpOAuthError(
        "ERR_PRISM_MCP_OAUTH_AUDIENCE",
        `protected resource ${parsed.origin} does not match the MCP server origin (confused-deputy denial)`,
      );
    }
    return parsed;
  }

  async saveDiscoveryState(state: OAuthDiscoveryState): Promise<void> {
    const metadata = state.authorizationServerMetadata;
    if (metadata?.issuer !== undefined) {
      let issuer: URL;
      try {
        issuer = new URL(metadata.issuer);
      } catch {
        throw new McpOAuthError("ERR_PRISM_MCP_OAUTH_ORIGIN", "authorization server metadata declared an invalid issuer");
      }
      if (issuer.origin !== new URL(state.authorizationServerUrl).origin) {
        throw new McpOAuthError(
          "ERR_PRISM_MCP_OAUTH_ORIGIN",
          `authorization server issuer ${issuer.origin} does not match the discovered AS origin`,
        );
      }
    }
    this.#assertStateBytes(state, "discovery state");
    await this.#options.state.saveDiscovery(state);
    this.#discoveryCache = { state, savedAt: this.#now() };
  }

  async discoveryState(): Promise<OAuthDiscoveryState | undefined> {
    if (!this.#discoveryLoaded) {
      this.#discoveryLoaded = true;
      const persisted = await this.#options.state.loadDiscovery();
      if (persisted) this.#discoveryCache = { state: persisted, savedAt: this.#now() };
    }
    const cached = this.#discoveryCache;
    if (cached && this.#now() - cached.savedAt < this.#limits.discoveryCacheTtlMs) return cached.state;
    return undefined;
  }

  async invalidateCredentials(scope: "all" | "client" | "tokens" | "verifier" | "discovery"): Promise<void> {
    this.#discoveryCache = undefined;
    await this.#options.state.clear(scope);
  }

  #assertStateBytes(value: unknown, label: string): void {
    const bytes = utf8Bytes(value);
    if (bytes > this.#limits.stateBytes) {
      throw new McpOAuthError("ERR_PRISM_MCP_OAUTH_STATE", `${label} exceeds ${this.#limits.stateBytes} bytes`);
    }
  }

  #assertRecordBytes(value: unknown, label: string): void {
    const bytes = utf8Bytes(value);
    if (bytes > this.#limits.tokenRecordBytes) {
      throw new McpOAuthError("ERR_PRISM_MCP_OAUTH_TOKEN_STORE", `${label} exceeds ${this.#limits.tokenRecordBytes} bytes`);
    }
  }
}

/** Build the OAuth client provider with Prism policy and persistence seams. */
export function createMcpClientAuth(
  options: McpClientAuthOptions,
  context: { readonly serverUrl: string | URL; readonly fetch: typeof fetch; readonly limits?: ResolvedMcpOAuthLimits },
): McpClientAuth {
  const limits = context.limits ?? resolveMcpOAuthLimits(options.limits);
  const provider = new PrismOAuthClientProvider(options, { serverUrl: context.serverUrl, fetch: context.fetch, limits });
  let inflight: Promise<"AUTHORIZED" | "REDIRECT"> | undefined;

  async function runAuth(input: { readonly scope?: string; readonly resourceMetadataUrl?: URL; readonly authorizationCode?: string }) {
    if (inflight) return inflight;
    inflight = sdkAuth(provider, {
      serverUrl: context.serverUrl,
      scope: input.scope,
      resourceMetadataUrl: input.resourceMetadataUrl,
      authorizationCode: input.authorizationCode,
      fetchFn: context.fetch,
    }).finally(() => {
      inflight = undefined;
    });
    return inflight;
  }

  return {
    provider,
    ensureAuthorized: (input) => runAuth({ scope: input?.scope, resourceMetadataUrl: input?.resourceMetadataUrl }),
    async finishAuth(authorizationCode: string) {
      if (!options.redirectUri) {
        throw new McpOAuthError("ERR_PRISM_MCP_OAUTH_STATE", "authorization code flow requires redirectUri");
      }
      const result = await runAuth({ authorizationCode });
      if (result !== "AUTHORIZED") throw new McpOAuthError("ERR_PRISM_MCP_OAUTH_STATE", "authorization code exchange did not complete");
    },
    async revoke() {
      const tokens = await options.state.loadTokens();
      const discovery = await options.state.loadDiscovery();
      const metadata = discovery?.authorizationServerMetadata;
      const revocationUrl = metadata && "revocation_endpoint" in metadata ? metadata.revocation_endpoint : undefined;
      if (tokens && revocationUrl) {
        const token = tokens.refresh_token ?? tokens.access_token;
        const params = new URLSearchParams({
          token,
          token_type_hint: tokens.refresh_token ? "refresh_token" : "access_token",
        });
        const headers = new Headers({ "content-type": "application/x-www-form-urlencoded" });
        const clientInformation = await provider.clientInformation();
        if (clientInformation) {
          const supported =
            metadata && "token_endpoint_auth_methods_supported" in metadata ? metadata.token_endpoint_auth_methods_supported : undefined;
          applyClientAuth(
            headers,
            params,
            selectClientAuthMethod(clientInformation, supported ?? []),
            clientInformation.client_id,
            clientInformation.client_secret,
          );
        }
        const response = await context.fetch(revocationUrl, {
          method: "POST",
          headers,
          body: params.toString(),
          redirect: "manual",
        });
        if (response.status >= 300) {
          await response.body?.cancel();
          throw new McpOAuthError("ERR_PRISM_MCP_OAUTH_TOKEN_STORE", `token revocation failed with HTTP ${response.status}`, {
            cause: new Error(await response.text().catch(() => "")),
          });
        }
        await response.body?.cancel();
      }
      await options.state.clear("tokens");
    },
    getTokens: () => options.state.loadTokens(),
  };
}

export type { AuthorizationServerMetadata };
